FROM node:12 as build-stage

LABEL image=build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install --no-optional && npm cache clean --force
COPY ./ .
RUN rm -rf dist
RUN npm run build

####

FROM nginx:alpine as production-stage

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY .htpasswd /etc/nginx/.htpasswd
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./fetch_env.js /etc/nginx/fetch_env.js
